<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMwP7oiO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMwP7oiO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMwP7oiO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMwP7oiO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMwP7oiO\App_KernelDevDebugContainer([
    'container.build_hash' => 'MwP7oiO',
    'container.build_id' => 'b762a41f',
    'container.build_time' => 1581426395,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMwP7oiO');
